# Generated by Django 3.1.4 on 2020-12-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locode', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=256)),
                ('name_wo', models.CharField(max_length=256)),
                ('sub_div', models.CharField(max_length=3)),
                ('func', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=2)),
                ('date', models.CharField(max_length=32)),
                ('iata', models.CharField(max_length=256)),
                ('coordinates', models.CharField(max_length=64)),
                ('remarks', models.CharField(max_length=256)),
            ],
        ),
    ]
